### ISSUE TITLE
InvalidArgumentsError: Incompatible shapes

### ISSUE THREAD

**Issue by MohamedSinger** [DebeshJha/2020-CBMS-DoubleU-Net#15]
When I try to run the code with ISIC 2017 skin lesion dataset I get the following error:
```
Epoch 1/10
Traceback (most recent call last):
  File "/content/drive/MyDrive/newceal/src/CEAL.py", line 81, in <module>
    shuffle=False)
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "/content/drive/MyDrive/newceal/src/CEAL.py", line 81, in <module>
      shuffle=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1009, in step_function
      data = next(iterator)
Node: 'IteratorGetNext'
Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "/content/drive/MyDrive/newceal/src/CEAL.py", line 81, in <module>
      shuffle=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1009, in step_function
      data = next(iterator)
Node: 'IteratorGetNext'
2 root error(s) found.
  (0) INVALID_ARGUMENT:  Incompatible shapes at component 0: expected [?,384,512,3] but got [32,512,384,3].
	 [[{{node IteratorGetNext}}]]
	 [[assert_less_equal/Assert/AssertGuard/else/_11/assert_less_equal/Assert/AssertGuard/Assert/data_0/_328]]
  (1) INVALID_ARGUMENT:  Incompatible shapes at component 0: expected [?,384,512,3] but got [32,512,384,3].
	 [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_15637]
```
I passed the data through the data.py class normally and I tried changing tensorflow and keras to multiple other versions but nothing seems to work

**Comment by siriasadeddin** [comment]
I had to do this 

```
def read_image(x):
    image = cv2.imread(x, cv2.IMREAD_COLOR)
    image = cv2.resize(image,(512,384)) #new code
    image = np.clip(image - np.median(image)+127, 0, 255)
    image = image/255.0
    image = image.astype(np.float32)
    image = np.expand_dims(image, axis=0)
    return image

def read_mask(y):
    mask = cv2.imread(y, cv2.IMREAD_GRAYSCALE)
    mask = cv2.resize(mask,(512,384)) #new code
    mask = mask.astype(np.float32)
    mask = mask/255.0
    mask = np.expand_dims(mask, axis=-1)
    return mask
```

But I am not sure if there is another way of fixing it without changing the code :/
